class10/movie_app/config/routes.rb
MovieApp::Application.routes.draw do

  root to: "movies#index"
  
  get 'movies/search', to: 'movies#search', as: "movies_search"

  resources :movies
  

  

end

class10/movie_app/app/models/movie.rb
class Movie < ActiveRecord::Base
	validates_presence_of :title 

	validates_length_of :description, :minimum => 10
end

class10/movie_app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.all		
		@movie = Movie.new

	end

	def show 
		@movie = Movie.find(params[:id])
	end

	def search
		@query = params[:batman]
		@movies = Movie.where('title LIKE ? OR description LIKE ?', "%#{@query}%", "%#{@query}%")
    	render 'movie_search'
	end	
	
	def new
		@movie = Movie.new
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		movie = Movie.find(params[:id])

	    if movie.update_attributes(movie_params)
	      redirect_to movie_path(movie)
	    else
	      flash[:alert] = movie.errors.full_messages.to_sentence
	      redirect_to edit_movie_path(movie)
	    end		
	end

	def create
		movie = Movie.new(movie_params)

	    if movie.save
	      redirect_to movies_path
	    else
	      flash[:alert] = movie.errors.full_messages.to_sentence 
	      redirect_to new_movie_path
	    end		
	end

	def destroy
		movie = Movie.find(params[:id])
	
		movie.destroy 

		redirect_to movies_path
	end

	private

	def movie_params
		params.require(:movie).permit(:title, :description)
	end

end

class10/movie_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

class10/movie_app/app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>  

  <div>
    <%= f.submit %>
  </div>
<% end %>

class10/movie_app/app/views/movies/_movies_list.html.erb
<ol>
	<% @movies.each do |film| %>
	  <li>
	  	<%= link_to movie_path(film) do %>
	      <p>
	        <%= film.title %> 
	        <!-- Diplays movie name -->
	      </p>
	    <% end %>
	      <p>
	        <%= film.description %> 
	        <!-- Diplays movie description -->
	      </p>	    	    
	  </li>
	<% end %>
</ol>

class10/movie_app/app/views/movies/edit.html.erb
<h2>This is the edit page</h2>

<p>
  <%= button_to 'Delete Movie', {action: 'destroy', id: @movie.id},method: 'delete' %>
</p>

<% if flash[:alert].present? %>
  <p class="errors">
    <%= flash[:alert] %>
  </p>
<% end %>

<%= render partial: 'form' %>

class10/movie_app/app/views/movies/index.html.erb
<h2>Welcome to RetFlix!</h2>

<%= form_for @movie do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>  

  <div>
    <%= f.submit %>
  </div>
<% end %>

<h3>All Movies List</h3>

<%= form_tag movies_search_path, method: :get do %>
  <%= label_tag(:batman, "Search for:") %>
  <%= text_field_tag(:batman) %>
  <%= submit_tag("Search") %>
<% end %>

<ol>
	<% @movies.each do |film| %>
	  <li>
	  	<%= link_to movie_path(film) do %>
	      <p>
	        <%= film.title %> <!-- Diplays movie name -->
	      </p>
	    <% end %>
	      <p>
	        <%= film.description %> <!-- Diplays movie description -->
	      </p>	    	    
	  </li>
	<% end %>
</ol>

class10/movie_app/app/views/movies/movie_search.html.erb
<h2>Movie Search Result</h2>

<p>You searched for <%= @query %></p>

<%= render partial: 'movies_list' %>

class10/movie_app/app/views/movies/new.html.erb
<h1>Create a New Shirt</h1>

<% if flash[:alert].present? %>
  <p class="errors">
    <%= flash[:alert] %>
  </p>
<% end %>

<%= render partial: 'form' %>

class10/movie_app/app/views/movies/show.html.erb
<h1>Show Each Movie Detail</h1>

<p>
  <%= link_to 'Edit', edit_movie_path(@movie) %>
</p>
<p>
  Title: <%= @movie.title %>
</p>
<p>
  Description: <%= @movie.description %>
</p>